name: Run Morpheus Task

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run curl command
        env:
          APPLIANCE_URL: ${{ secrets.MORPHEUS_APPLIANCE_URL }}
          API_TOKEN: ${{ secrets.MORPHEUS_API_TOKEN }}
        run: |
          curl --request POST \
            --url $APPLIANCE_URL/api/tasks \
            --header "Authorization: Bearer $API_TOKEN" \
            --header 'Content-Type: application/json' \
            --data '{
            "task": {
              "visibility": "private",
              "taskType": {
                "code": "groovyTask"
              },
              "taskOptions": {},
              "executeTarget": "local",
              "retryable": false,
              "file": {
                "sourceType": "url",
                "contentUrl": "https://raw.githubusercontent.com/uthm4n/goomba-shuffler/main/api/updateInterfaces.groovy"
              },
              "name": "GoombaShuffle",
              "code": "network-interface-updater"
            }
          }'
